name: Publish Early

on:
  workflow_dispatch:

jobs:
  publish-linux:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    #if: ${{ github.repository_owner === 'electron-react-boilerplate' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Set Early Build
        run: |
          sed -i "s|main|early|g" "./src/data/branch.json"
          sed -i "s|emudeck-electron|emudeck-electron-early|g" "./package.json"
          #sed -i "s|EmuDeck|EmuDeck-early|g" "./release/app/package.json"
          #sed -i 's|"productName": "EmuDeck"|"productName": "EmuDeck-early"|g' "./package.json"

      - name: Publish releases
        env:
          
          GH_TOKEN: ${{ secrets.gh_token }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always --linux

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: EmuDeck-Early-AppImage
          path: '**/*.AppImage'
  publish-windows:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Set Early Build
        run: |
          sed -i'.original' -e "s|main|early|g" "./src/data/branch.json"
          sed -i'.original' -e "s|emudeck-electron|emudeck-electron-early|g" "./package.json"
          #sed -i'.original' -e "s|EmuDeck|EmuDeck-early|g" "./release/app/package.json"
          #sed -i'.original' -e 's|"productName": "EmuDeck"|"productName": "EmuDeck-early"|g' "./package.json"
      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always --win
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: EmuDeck-early-windows
          path: '**/*.exe'
